//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

pub mod prelude;

pub mod authrecord;
pub mod customer;
pub mod employee;
pub mod kiosk;
pub mod products;
pub mod promotion;
pub mod sea_orm_active_enums;
pub mod session;
pub mod store;
pub mod supplier;
pub mod tenants;
pub mod transactions;
