//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

pub use super::customer::Entity as Customer;
pub use super::employee::Entity as Employee;
pub use super::products::Entity as Products;
pub use super::promotion::Entity as Promotion;
pub use super::session::Entity as Session;
pub use super::store::Entity as Store;
pub use super::supplier::Entity as Supplier;
pub use super::transactions::Entity as Transactions;
