//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Products")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub sku: String,
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub company: String,
    pub variants: Json,
    pub variant_groups: Json,
    pub images: Json,
    pub tags: Json,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub specifications: Json,
    pub identification: Json,
    pub visible: Json,
    pub name_long: String,
    pub description_long: String,
    pub tenant_id: String,

    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
