//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

use super::sea_orm_active_enums::TransactionType;
use sea_orm::entity::prelude::*;
use std::convert::TryInto;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Transactions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub customer: String,
    pub transaction_type: TransactionType,
    pub products: Json,
    pub order_total: i32,
    pub payment: Json,
    pub order_date: DateTime,
    pub order_notes: Json,
    pub order_history: Json,
    #[sea_orm(column_type = "Text")]
    pub salesperson: String,
    #[sea_orm(column_type = "Text")]
    pub till: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
